version: 2.1

jobs:
  build:
    machine:
        image: android:202102-01
    steps:
    - checkout
    - run:
        name: Install Appium
        command: npm install -g appium@next --unsafe-perm=true
