version: 2.1

jobs:
  build:
    machine:
      image: android:2023.05
    resource_class: medium
    steps:
    - checkout
    - run:
        name: Install Appium
        command: npm install -g appium@next --unsafe-perm=true
